# Generated by Django 5.1.6 on 2025-05-24 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='estagiario',
            name='area',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='estagiarios', to='core.area'),
            preserve_default=False,
        ),
    ]
