# Generated by Django 5.1.6 on 2025-07-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_estagiario_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='estagiario',
            name='digital',
            field=models.CharField(default='', max_length=500),
        ),
    ]
