# Generated by Django 5.1.6 on 2025-08-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pushcommand_resultcommand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('unidade', models.CharField(max_length=100)),
                ('login', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='unidade',
            field=models.CharField(default='Campos Eliseos', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estagiario',
            name='unidade',
            field=models.CharField(default='Campos Eliseos', max_length=100),
            preserve_default=False,
        ),
    ]
