# Generated by Django 5.1.6 on 2025-08-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_usuario_area_unidade_estagiario_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='login',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
