# Generated by Django 5.1.6 on 2025-08-21 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_usuario_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estagiario',
            name='digital',
        ),
    ]
