# Generated by Django 5.1.6 on 2025-08-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_estagiario_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='estagiario',
            name='control_id_user_id',
            field=models.CharField(blank=True, help_text='ID do usuário no Control ID', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='estagiario',
            name='digital',
            field=models.CharField(default='', max_length=500),
        ),
    ]
