# Generated by Django 5.1.6 on 2025-08-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_estagiario_control_id_user_id_estagiario_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenca',
            name='presente',
            field=models.BooleanField(default=True, help_text='Indica se o estagiário está presente (True) ou ausente (False)'),
        ),
    ]
