# Generated by Django 5.1.6 on 2025-08-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_presenca_presente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presenca',
            name='presente',
        ),
        migrations.AddField(
            model_name='estagiario',
            name='presente',
            field=models.BooleanField(default=True, help_text='Indica se o estagiário está presente (True) ou ausente (False)'),
        ),
    ]
