# Generated by Django 5.1.6 on 2025-08-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_presenca_presente_estagiario_presente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estagiario',
            name='presente',
            field=models.BooleanField(default=False, help_text='Indica se o estagiário está presente (True) ou ausente (False)'),
        ),
    ]
