# Generated by Django 5.1.6 on 2025-08-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_estagiario_presente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenca',
            name='entrada',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
