# Generated by Django 5.1.6 on 2025-08-21 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_presenca_entrada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estagiario',
            name='digital',
        ),
    ]
