# Generated by Django 5.1.6 on 2025-09-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_estagiario_digital'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleColetaLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_timestamp', models.DateTimeField(blank=True, help_text='Timestamp do último log processado', null=True)),
                ('ultimo_log_id', models.CharField(blank=True, help_text='ID único do último log processado', max_length=32, null=True)),
                ('total_processados', models.IntegerField(default=0, help_text='Total de logs processados')),
                ('processed_log_ids', models.JSONField(default=list, help_text='Lista de IDs de logs já processados (cache)')),
            ],
            options={
                'verbose_name': 'Controle de Coleta de Logs',
                'verbose_name_plural': 'Controles de Coleta de Logs',
            },
        ),
    ]
