# Generated by Django 5.1.6 on 2025-09-04 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_unidade_usuariounidade_delete_pushcommand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estagiario',
            name='unidade',
        ),
        migrations.RemoveField(
            model_name='estagiario',
            name='unidade_deprecated',
        ),
    ]
