# Generated by Django 5.1.6 on 2025-09-04 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_estagiario_unidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estagiario',
            name='unidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='estagiarios', to='core.unidade'),
            preserve_default=False,
        ),
    ]
