# Generated by Django 5.1.6 on 2025-09-04 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_estagiario_unidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='unidade',
        ),
    ]
