# Generated by Django 5.1.6 on 2025-09-04 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_area_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='unidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='core.unidade'),
            preserve_default=False,
        ),
    ]
