# Generated by Django 5.1.6 on 2025-10-04 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_usuario_unidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estagiario',
            name='telefone',
        ),
    ]
