# Generated by Django 5.1.6 on 2025-10-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_estagiario_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='descricao',
        ),
        migrations.AddField(
            model_name='estagiario',
            name='data_efetivacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estagiario',
            name='efetivado',
            field=models.BooleanField(default=False),
        ),
    ]
