# Generated by Django 5.1.6 on 2025-10-04 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_area_descricao_estagiario_data_efetivacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estagiario',
            name='data_efetivacao',
        ),
    ]
