# Generated by Django 5.1.6 on 2025-10-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_estagiario_data_efetivacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='estagiario',
            name='setor',
            field=models.CharField(choices=[('tecnologia', 'Tecnologia'), ('financeiro', 'Financeiro'), ('pedagogia', 'Pedagogia'), ('educação física', 'Educação Física')], default='tecnologia', max_length=100),
            preserve_default=False,
        ),
    ]
