# Generated by Django 5.1.6 on 2025-10-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_estagiario_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='setor',
            field=models.CharField(choices=[('tecnologia', 'Tecnologia'), ('financeiro', 'Financeiro'), ('pedagogia', 'Pedagogia'), ('educação física', 'Educação Física')], default='Tecnologia', max_length=100),
            preserve_default=False,
        ),
    ]
