# Generated by Django 5.1.6 on 2025-10-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_area_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariounidade',
            name='nivel_acesso',
            field=models.CharField(choices=[('leitura', 'Leitura'), ('admin', 'Admin')], max_length=50),
        ),
    ]
