# Generated by Django 5.1.6 on 2025-11-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_usuariounidade_nivel_acesso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome identificador do sensor', max_length=100)),
                ('ip', models.CharField(help_text='Endereço IP do sensor Control ID', max_length=15)),
                ('porta', models.IntegerField(default=81, help_text='Porta do sensor Control ID')),
                ('ativo', models.BooleanField(default=True, help_text='Se o sensor está ativo para coleta')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensores',
            },
        ),
        migrations.AlterField(
            model_name='controlecoletalogs',
            name='processed_log_ids',
            field=models.JSONField(default=list, help_text='Lista de IDs de logs já processados para este sensor (cache)'),
        ),
        migrations.AlterField(
            model_name='controlecoletalogs',
            name='total_processados',
            field=models.IntegerField(default=0, help_text='Total de logs processados para este sensor'),
        ),
        migrations.AlterField(
            model_name='controlecoletalogs',
            name='ultimo_log_id',
            field=models.CharField(blank=True, help_text='ID único do último log processado para este sensor', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='controlecoletalogs',
            name='ultimo_timestamp',
            field=models.DateTimeField(blank=True, help_text='Timestamp do último log processado para este sensor', null=True),
        ),
        migrations.AlterField(
            model_name='estagiario',
            name='setor',
            field=models.CharField(choices=[('tecnologia', 'Tecnologia'), ('financeiro', 'Financeiro'), ('pedagogia', 'Pedagogia'), ('educação física', 'Educação Física'), ('manutenção', 'Manutenção')], max_length=100),
        ),
    ]
