# Generated by Django 5.1.6 on 2025-11-18 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_sensor_alter_controlecoletalogs_processed_log_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlecoletalogs',
            name='sensor',
            field=models.ForeignKey(default=1, help_text='Sensor associado ao controle', on_delete=django.db.models.deletion.CASCADE, to='core.sensor'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='controlecoletalogs',
            unique_together={('sensor',)},
        ),
    ]
