# Generated by Django 5.1.6 on 2025-11-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_controlecoletalogs_sensor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='device_id',
            field=models.CharField(blank=True, help_text='ID do dispositivo no Control ID para Monitor', max_length=50, null=True),
        ),
    ]
