# Generated by Django 5.1.6 on 2025-11-19 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_sensor_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='unidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sensores', to='core.unidade'),
            preserve_default=False,
        ),
    ]
