# Generated by Django 5.1.6 on 2025-11-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_sensor_unidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estagiario',
            name='email',
        ),
        migrations.AlterField(
            model_name='area',
            name='setor',
            field=models.CharField(choices=[('tecnologia', 'Tecnologia'), ('rh', 'Recursos Humanos'), ('pedagogia', 'Pedagogia'), ('educação física', 'Educação Física'), ('Enfermagem', 'Enfermagem'), ('Administração', 'Administração')], max_length=100),
        ),
        migrations.AlterField(
            model_name='estagiario',
            name='setor',
            field=models.CharField(choices=[('tecnologia', 'Tecnologia'), ('rh', 'Recursos Humanos'), ('pedagogia', 'Pedagogia'), ('educação física', 'Educação Física'), ('Enfermagem', 'Enfermagem'), ('Administração', 'Administração')], max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='area',
            field=models.CharField(choices=[('tecnologia', 'Tecnologia'), ('rh', 'Recursos Humanos'), ('pedagogia', 'Pedagogia'), ('educação física', 'Educação Física'), ('Enfermagem', 'Enfermagem'), ('Administração', 'Administração')], max_length=100),
        ),
    ]
